name: GitHub Trending

on:
  schedule:
    - cron: '0 0 * * *' # 每天 UTC 时间 00:00 运行 (北京时间早上 8:00)
  workflow_dispatch: # 允许手动触发

jobs:
  fetch-trending:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # 或其他你需要的版本

      - name: Install requirements
        run: pip install requests beautifulsoup4

      - name: Fetch and save trending data
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 用于提交更改
        run: |
          python fetch_trending.py

      - name: Commit and push changes
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs')
            const now = new Date().toISOString().slice(0, 10)
            const filename = `trending_${now}.json`
            if (fs.existsSync(filename)) {
              await github.rest.git.createBlob({
                owner: context.repo.owner,
                repo: context.repo.repo,
                content: fs.readFileSync(filename, { encoding: 'base64' }),
                encoding: 'base64'
              })
              const { data: tree } = await github.rest.git.createTree({
                owner: context.repo.owner,
                repo: context.repo.repo,
                tree: [
                  {
                    path: filename,
                    mode: '100644',
                    type: 'blob',
                    sha: blob.data.sha,
                  },
                ],
                base_tree: context.sha
              })
              const { data: commit } = await github.rest.git.createCommit({
                owner: context.repo.owner,
                repo: context.repo.repo,
                message: `Update trending data ${now}`,
                tree: tree.sha,
                parents: [context.sha],
              })
              await github.rest.git.updateRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: 'heads/main', // 或者 'heads/master'，取决于你的默认分支
                sha: commit.sha,
              })
            } else {
                console.log("No trending data file found.")
            }