name: GitHub Trending

on:
  schedule:
    - cron: '0 0 * * *' # 每天 UTC 时间 00:00 运行
  workflow_dispatch: # 允许手动触发 workflow

jobs:
  fetch-trending:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install requirements
        run: pip install requests beautifulsoup4

      - name: Fetch and save trending data
        run: python fetch_trending.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add trending/*.json # 添加 trending 文件夹下的所有 JSON 文件
          git commit -m "Update trending data $(date +%Y-%m-%d)"
          git push origin main # 或 master，取决于你的默认分支